config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :cron_requests do 
    	get '/logs' => 'cron_requests#logs'
    	get '/run_now' => 'cron_requests#run_now'
    end
  end
  devise_for :users

  root to: "admin/cron_requests#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/admin/cron_request.rb
require 'net/https'
require 'json'
require 'logger'

class Admin::CronRequest < ApplicationRecord
	has_many :cron_request_logs
	after_save :update_whenever_file

	validates :title, presence: true
	validates :url, presence: true, url_check: true
	validates :http_method, presence: true

	def run!
		logger = Logger.new(STDOUT) 
		uri = URI(self.url)
		
		http = Net::HTTP.new uri.host, uri.port

		request = Net::HTTP::Post.new(uri.request_uri)

		if self.http_method == "GET"
			request = Net::HTTP::Get.new(uri.request_uri)
		elsif self.http_method == "POST"
			request = Net::HTTP::Post.new(uri.request_uri)
		else
			logger.info("No method error!")
		end

		request.set_form_data(JSON.parse(self.params)) if not self.params.blank?

		http.read_timeout = 200
		http.use_ssl = true if self.url.include? "https"
		http.verify_mode = OpenSSL::SSL::VERIFY_NONE
	  begin
	    response = http.request(request)
	    responseMessage =  response.body
	    responseCode = response.code.to_i
	  rescue Exception => e 
	    responseMessage = e.message
	    responseCode = -1
	  end
		Admin::CronRequestLog.create({cron_request_id: self.id, status_code: responseCode, response:responseMessage})
	end

	def parse_to_whenever
	    hour = ""
	    hour = ", :at => '#{self.at}' " if not self.at.blank?
	<<-DOC
	every #{self.periodicity}.#{self.periodicity_type}#{hour} do 
	  runner "Admin::CronRequest.find(#{self.id}).run!"
	end	

	DOC

	end

	def update_whenever_file
	  	File.open('./config/schedule.rb', 'w+') do |f|
	  		f.puts "set :output, './log/automagick.cron.log'"
	  		Admin::CronRequest.where(status: 1).each do |cron_request|
	  			f.puts cron_request.parse_to_whenever
	  		end
	  	end

	  	`whenever --update-crontab automagick.coredigital.com.br_production`
	end
end

app/models/admin/cron_request_log.rb
class Admin::CronRequestLog < ApplicationRecord
	belongs_to :cron_request
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cron_requests, class_name: 'Admin::CronRequest'
end

app/controllers/admin/cron_requests_controller.rb
class Admin::CronRequestsController < ApplicationController
  before_action :set_admin_cron_request, only: [:show, :edit, :update, :destroy]

  before_action :authenticate_user!

  # GET /admin/cron_requests
  # GET /admin/cron_requests.json
  def index
    @admin_cron_requests = Admin::CronRequest.all
  end

  # GET /admin/cron_requests/1
  # GET /admin/cron_requests/1.json
  def show
  end

  # GET /admin/cron_requests/new
  def new
    @admin_cron_request = Admin::CronRequest.new
  end

  # GET /admin/cron_requests/1/edit
  def edit
  end

  # POST /admin/cron_requests
  # POST /admin/cron_requests.json
  def create
    @admin_cron_request = Admin::CronRequest.new(admin_cron_request_params)

    respond_to do |format|
      if @admin_cron_request.save
        format.html { redirect_to @admin_cron_request, notice:  I18n.t('admin.cron_requests.create.message.success') }
        format.json { render :show, status: :created, location: @admin_cron_request }
      else
        format.html { render :new }
        format.json { render json: @admin_cron_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/cron_requests/1
  # PATCH/PUT /admin/cron_requests/1.json
  def update
    respond_to do |format|
      if @admin_cron_request.update(admin_cron_request_params)
        format.html { redirect_to @admin_cron_request, notice:  I18n.t('admin.cron_requests.update.message.success')  }
        format.json { render :show, status: :ok, location: @admin_cron_request }
      else
        format.html { render :edit }
        format.json { render json: @admin_cron_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/cron_requests/1
  # DELETE /admin/cron_requests/1.json
  def destroy
    @admin_cron_request.destroy
    respond_to do |format|
      format.html { redirect_to admin_cron_requests_url, notice:   I18n.t('admin.cron_requests.destroy.message.success')  }
      format.json { head :no_content }
    end
  end

  def logs
    @admin_cron_request_logs = Admin::CronRequest.find(params[:cron_request_id]).cron_request_logs.order("id DESC")
  end

  def run_now
    @admin_cron_request = Admin::CronRequest.find(params[:cron_request_id])
    @admin_cron_request.run!
    respond_to do |format|
      format.html { redirect_to admin_cron_requests_url, notice:   I18n.t('admin.cron_requests.run_now.message.success')  }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_cron_request
      @admin_cron_request = Admin::CronRequest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_cron_request_params
      params.require(:admin_cron_request).permit(:title, :description, :url, :http_method, :periodicity, :at, :status, :user_id, :periodicity_type, :params)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/cron_requests_helper.rb
module Admin::CronRequestsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/cron_requests/_form.html.erb
<%= form_with(model: admin_cron_request, local: true, class: "form-horizontal form-label-left") do |form| %>
  <% if admin_cron_request.errors.any? %>
    <div id="error_explanation" class="alert alert-danger alert-dismissible fade in">
      <h2><%= pluralize(admin_cron_request.errors.count, "error") %> <%=t("message.prohibited_saved")%></h2>

      <ul>
      <% admin_cron_request.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title,t(".label_title"), :class=>"control-label col-md-3 col-sm-3 col-xs-12" %>
    <div class="col-md-6 col-sm-6 col-xs-12"><%= form.text_field :title, :class=>"form-control col-md-7 col-xs-12" %></div>
  </div>

  <div class="form-group">
    <%= form.label :description, t(".label_description"), :class=>"control-label col-md-3 col-sm-3 col-xs-12" %>
    <div class="col-md-6 col-sm-6 col-xs-12"><%= form.text_area :description, :class=>"form-control col-md-7 col-xs-12" %></div>
  </div>

  <div class="form-group">
    <%= form.label :url, t(".label_url"), :class=>"control-label col-md-3 col-sm-3 col-xs-12" %>
    <div class="col-md-6 col-sm-6 col-xs-12"><%= form.text_field :url, :class=>"form-control col-md-7 col-xs-12" %></div>
  </div>

  <div class="form-group">
    <%= form.label :http_method, t(".label_http_method"), :class=>"control-label col-md-3 col-sm-3 col-xs-12" %>
    <div class="col-md-6 col-sm-6 col-xs-12"><%= form.text_field :http_method, :class=>"form-control col-md-7 col-xs-12" %></div>
  </div>

  <div class="form-group">
    <%= form.label :periodicity, t(".label_periodicity"), :class=>"control-label col-md-3 col-sm-3 col-xs-12" %>
    <div class="col-md-6 col-sm-6 col-xs-12">
      <%= form.select(:periodicity, options_for_select([['1', '1'], ['5', '5'], ['10', '10'], ['15', '15'], ['20', '20']], @admin_cron_request.periodicity), {},{:class=>"form-control col-md-7 col-xs-12"}) %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :periodicity_type, t(".label_periodicity_type"), :class=>"control-label col-md-3 col-sm-3 col-xs-12" %>
    <div class="col-md-6 col-sm-6 col-xs-12">
      <%= form.select(:periodicity_type, options_for_select([['Minuto(s)', 'minutes'], ['Hora(s)', 'hours'], ['Dia(s)', 'days'], ['Mes(es)', 'months']], @admin_cron_request.periodicity_type), {},{:class=>"form-control col-md-7 col-xs-12"}) %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :at, t(".label_at"),:class=>"control-label col-md-3 col-sm-3 col-xs-12" %>
    <div class="col-md-6 col-sm-6 col-xs-12">
         <%options = Array.new %>
    <% options << ['', ''] %>
    <% 12.times{|t| options << ["#{t + 1}:00 am", "#{t + 1}:00 am"]; options << ["#{t + 1}:30 am", "#{t + 1}:30 am"]} %>
    <% 12.times{|t| options << ["#{t + 1}:00 pm", "#{t + 1}:00 pm"]; options << ["#{t + 1}:30 pm", "#{t + 1}:30 pm"]} %>
    <%= form.select(:at, options_for_select(options, @admin_cron_request.at), {},{:class=>"form-control col-md-7 col-xs-12"}) %>

    </div>
  </div>

  <div class="form-group">
    <%= form.label :status,t(".label_status"), :class=>"control-label col-md-3 col-sm-3 col-xs-12" %>
    <div class="col-md-6 col-sm-6 col-xs-12"><%= form.check_box :status, :class=>"form-control col-md-7 col-xs-12" %></div>
  </div>

  <div class="form-group">
    <%= form.label :user_id, :class=>"control-label col-md-3 col-sm-3 col-xs-12" %>
   <div class="col-md-6 col-sm-6 col-xs-12"> <%= form.number_field :user_id, :class=>"form-control col-md-7 col-xs-12" %></div>
  </div>

  <div class="form-group">
    <%= form.label :params, t(".label_params"), :class=>"control-label col-md-3 col-sm-3 col-xs-12" %>
    <div class="col-md-6 col-sm-6 col-xs-12"><%= form.text_field :params, :class=>"form-control col-md-7 col-xs-12" %></div>
  </div>
  <div class="ln_solid"></div>
  <div class="form-group">
    <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
      <%= form.submit t("button.send"), :class=>"btn btn-success" %>
    </div>
  </div>
<% end %>

app/views/admin/cron_requests/edit.html.erb
<h1>Editing Admin Cron Request</h1>

<%= render 'form', admin_cron_request: @admin_cron_request %>

<%= link_to 'Show', @admin_cron_request %> |
<%= link_to 'Back', admin_cron_requests_path %>

app/views/admin/cron_requests/index.html.erb
<p id="notice"><%= notice %></p>

<div class="x_panel">

<div class="x_title">
<h2><%= t('.title_page')%></h2>
<div class="clearfix"></div>
</div>

<div class="x_content">
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= t('.table_header_title')%></th>
      <th><%= t('.table_header_url')%></th>
      <th><%= t('.table_header_periodicity')%></th>
      <th><%= t('.table_header_status')%></th>
      <th><%= t('.table_header_params')%></th>
      <th colspan="5"><%= t('.table_header_actions')%></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_cron_requests.each do |admin_cron_request| %>
      <tr>
        <td><%= admin_cron_request.title %> <br/><%= admin_cron_request.description %></td>
        <td><%= admin_cron_request.url %> - <%= admin_cron_request.http_method %></td>
        <td><%= admin_cron_request.periodicity %> at <%= admin_cron_request.at %></td>
        <td><%= admin_cron_request.status %></td>
        <td><%= admin_cron_request.params %></td>
        <td><%= link_to t('button.show'), admin_cron_request %></td>
        <td><%= link_to t('button.edit'), edit_admin_cron_request_path(admin_cron_request) %></td>
        <td><%= link_to t('button.destroy'), admin_cron_request, method: :delete, data: { confirm: t('button.destroy') } %></td>
        <td><%= link_to t('.table_label_log_action'), admin_cron_request_logs_url(admin_cron_request)%></td>
        <td><%= link_to t('.table_label_run_manually_action'), admin_cron_request_run_now_url(admin_cron_request)%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('.new_button'), new_admin_cron_request_path, :class=>"btn btn-success" %>
</div>
</div>

app/views/admin/cron_requests/logs.html.erb
<div class="row">
  <div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
      <div class="x_title">
          <h2><%= t(".title_page") %></h2>
          <div class="clearfix"></div>
      </div>

      <div class="x_content">
        <% if @admin_cron_request_logs.count > 0 %>
        <table class="table table-striped">
           <thead>
          <tr>
            <th><%=t(".table_header_datetime")%></th>
            <th><%=t(".table_header_http_status_code")%></th>
            <th><%=t(".table_header_response")%></th>
          </tr>
          </thead>

        <% @admin_cron_request_logs.each do |admin_cron_request_log| %>
          <tr>
            <td><%= admin_cron_request_log.created_at %></td>
            <td><%= admin_cron_request_log.status_code %></td>
            <td><pre><%= admin_cron_request_log.response %></pre></td>
          </tr>
        <% end %>
        </table>
        <% else %>
          <center><%=t("message.no_records")%></center>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/cron_requests/new.html.erb
<div class="row">
	<div class="col-md-12 col-sm-12 col-xs-12">
		<div class="x_panel">
			<div class="x_title">
			    <h2><%= t(".title_page") %></h2>
			    <div class="clearfix"></div>
		  </div>

		  <div class="x_content">
			<%= render 'form', admin_cron_request: @admin_cron_request %>
			<%= link_to t("button.back"), admin_cron_requests_path %>
		  </div>
		</div>
	</div>
</div>

app/views/admin/cron_requests/show.html.erb
<div class="row">
  <div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
      <div class="x_title">
          <h2><%= t(".title_page") %></h2>
          <div class="clearfix"></div>
      </div>

      <div class="x_content">
        
<p id="notice"><%= notice %></p>

<p>
  <strong><%=t(".label_title")%></strong>
  <%= @admin_cron_request.title %>
</p>

<p>
  <strong><%=t(".label_description")%></strong>
  <%= @admin_cron_request.description %>
</p>

<p>
  <strong><%=t(".label_url")%></strong>
  <%= @admin_cron_request.url %>
</p>

<p>
  <strong><%=t(".label_http_method")%></strong>
  <%= @admin_cron_request.http_method %>
</p>

<p>
  <strong><%=t(".label_periodicity")%></strong>
  <%= @admin_cron_request.periodicity %>
</p>

<p>
  <strong><%=t(".label_at")%></strong>
  <%= @admin_cron_request.at %>
</p>

<p>
  <strong><%=t(".label_status")%></strong>
  <%= @admin_cron_request.status %>
</p>

<p>
  <strong>User:</strong>
  <%= @admin_cron_request.user_id %>
</p>

<p>
  <strong><%=t(".label_params")%></strong>
  <%= @admin_cron_request.params %>
</p>

<%= link_to t("button.edit"), edit_admin_cron_request_path(@admin_cron_request) %> |
<%= link_to t("button.back"), admin_cron_requests_path %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <%= csrf_meta_tags %>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all' %>

    <title><%= yield :title %></title>
  </head>

  <body class="nav-md">
    <div class="container body">
      <div class="main_container">
        <div class="col-md-3 left_col">
          <div class="left_col scroll-view">
            <%= render partial: 'layouts/shared/leftnav' %>
          </div>
        </div>

        <!-- top navigation -->
        <div class="top_nav">
          <div class="nav_menu">
            <nav>
              <%= render partial: 'layouts/shared/topnav' %>
            </nav>
          </div>
        </div>
        <!-- /top navigation -->

        <!-- page content -->
        <div class="right_col" role="main">
          <%= yield %>
        </div>
        <!-- /page content -->

        <!-- footer content -->
        <footer>
          <%= render partial: 'layouts/shared/footer' %>
        </footer>
        <!-- /footer content -->
      </div>
    </div>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <%= csrf_meta_tags %>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all' %>

    <title><%= yield :title %></title>
  </head>

  <body class="login">
    <%= yield %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/layouts/shared/_footer.html.erb
<div class="pull-right">
  Rails 5.2
</div>
<div class="clearfix"></div>

app/views/layouts/shared/_leftnav.html.erb
<div class="navbar nav_title" style="border: 0;">
  <a href="/" class="site_title"><i class="fa fa-magic"></i> <span>Automagick</span></a>
</div>

<div class="clearfix"></div>

<!-- menu profile quick info -->
<div class="profile clearfix">
  <div class="profile_pic">
    <img src="https://raw.githubusercontent.com/mwlang/gentelella-rails-demo/master/examples/shared/public/images/img.jpg" alt="..." class="img-circle profile_img">
  </div>
  <div class="profile_info">
    <span><%=t("menu.welcome")%></span>
    <h2><%=current_user.email%></h2>
  </div>
</div>
<!-- /menu profile quick info -->

<br />

<!-- sidebar menu -->
<div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
  <div class="menu_section">
    <h3><%=t("menu.general")%></h3>
    <ul class="nav side-menu">
      <li><a><i class="fa fa-home"></i> <%=t('menu.home')%> <span class="fa fa-chevron-down"></span></a>
        <ul class="nav child_menu">
          <li>
            <%=link_to t('menu.cron_requests'), admin_cron_requests_url%></li>
        </ul>
      </li>
    </ul>
  </div>
</div>
<!-- /sidebar menu -->

<!-- /menu footer buttons -->
<div class="sidebar-footer hidden-small">
  <a data-toggle="tooltip" data-placement="top" title="Settings">
    <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
  </a>
  <%=link_to raw("<span class='glyphicon glyphicon-off' aria-hidden='true'></span>"), destroy_user_session_url, method: "Delete", data: {toggle: 'tooltip', placement: 'top'}, title: 'Logout'%>
</div>
<!-- /menu footer buttons -->

app/views/layouts/shared/_topnav.html.erb
<div class="nav toggle">
  <a id="menu_toggle"><i class="fa fa-bars"></i></a>
</div>

<ul class="nav navbar-nav navbar-right">
  <li class="">
    <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
      <img src="images/img.jpg" alt=""><%=current_user.email%>
      <span class=" fa fa-angle-down"></span>
    </a>
    <ul class="dropdown-menu dropdown-usermenu pull-right">
      <li><%=link_to t('link.profile'), edit_user_registration_url%></li>
      <li>
        <%=link_to raw("<i class='fa fa-sign-out pull-right'></i> #{t('link.logout')}"), destroy_user_session_url, method: "Delete" %>
      </li>
    </ul>
  </li>

  <li role="presentation" class="dropdown">
    <a href="javascript:;" class="dropdown-toggle info-number" data-toggle="dropdown" aria-expanded="false">
      <i class="fa fa-envelope-o"></i>
      <span class="badge bg-green">6</span>
    </a>
    <ul id="menu1" class="dropdown-menu list-unstyled msg_list" role="menu">
      <li>
        <a>
          <span class="image"><img src="images/img.jpg" alt="Profile Image" /></span>
          <span>
            <span>John Smith</span>
            <span class="time">3 mins ago</span>
          </span>
          <span class="message">
            Film festivals used to be do-or-die moments for movie makers. They were where...
          </span>
        </a>
      </li>
      <li>
        <a>
          <span class="image"><img src="images/img.jpg" alt="Profile Image" /></span>
          <span>
            <span>John Smith</span>
            <span class="time">3 mins ago</span>
          </span>
          <span class="message">
            Film festivals used to be do-or-die moments for movie makers. They were where...
          </span>
        </a>
      </li>
      <li>
        <a>
          <span class="image"><img src="images/img.jpg" alt="Profile Image" /></span>
          <span>
            <span>John Smith</span>
            <span class="time">3 mins ago</span>
          </span>
          <span class="message">
            Film festivals used to be do-or-die moments for movie makers. They were where...
          </span>
        </a>
      </li>
      <li>
        <a>
          <span class="image"><img src="images/img.jpg" alt="Profile Image" /></span>
          <span>
            <span>John Smith</span>
            <span class="time">3 mins ago</span>
          </span>
          <span class="message">
            Film festivals used to be do-or-die moments for movie makers. They were where...
          </span>
        </a>
      </li>
      <li>
        <div class="text-center">
          <a>
            <strong>See All Alerts</strong>
            <i class="fa fa-angle-right"></i>
          </a>
        </div>
      </li>
    </ul>
  </li>
</ul>